Fixes future prediction and other bugs
jasp-stats/jaspPredictiveAnalytics pull request #19
Opened 2023-11-07 15:10 UTC by petersen-f

This PR mainly fixes the prediction and adds options to make sure user can always predict the future as well as minor bugs:
- adds warning/error when covariates/factors but no training indicator is provided
- adds option for periodical prediction (same like prophet module) where future data frame for prediction is created that extends beyond provided data + warning that frequency and units should be the same as training data. this way user can predict future without having to provide training indicator/include in training variable
- forecast verification plot now also works with only one prediction model
- available models that can be computed are now based on qml logic and not R function which reduces bugs -> e.g. when no covariates are selected, user can only select autoregressive models
- fixes some minor things dependency issues and qml options as well as enabling weekly seasonality for the prophet module

2023-11-08 14:27 UTC, petersen-f commented on inst/qml/predictiveAnalytics.qml
> +					}
This function filters the available prediction models depending on whether they are possible based on the users input. For example one shouldn't be able to add a regression model like BART when no covariates are provided.
However, I discovered that the (selected) models in the qml elements are not saved when the JASP file is reopened. So one doesn't know anymore what models were selected for verification and prediction (although the JASP output/results persist).

I will try to fix this, please wait with approving this PR until then.

2023-11-08 20:37 UTC, petersen-f commented on inst/qml/predictiveAnalytics.qml
> +					}
I fixed it by creating a invisible availableVariableList that uses the function to make the right models available and then just use this as a source for a second availableVariableList that the user can see and use. this is a bit hacky, but works..

2023-11-30 11:48 UTC, petersen-f commented
This PR now closes issue [#2336](https://github.com/jasp-stats/INTERNAL-jasp/issues/2390),[#2390](https://github.com/jasp-stats/INTERNAL-jasp/issues/2339),[#2455](https://github.com/jasp-stats/jasp-test-release/issues/2455),[#2456](https://github.com/jasp-stats/jasp-test-release/issues/2456),[#2457](https://github.com/jasp-stats/jasp-test-release/issues/2457),[#2458](https://github.com/jasp-stats/jasp-test-release/issues/2458).

It adds quite a few warnings when inputs do not make sense, limits some of the qml options to sensible values and fixes some bugs that prevented computation.

2023-11-30 13:27 UTC, vandenman requested changes

2023-11-30 13:27 UTC, vandenman commented on R/predictiveAnalytics.R
> +        "If you just want to check how well the predictions perform historically you can choose the option 'No forecast - verification only'")))
you cannot use `paste` inside `gettext`, please format this as a single string. The same goes for the check below.

2023-11-30 13:27 UTC, vandenman commented on R/predictiveAnalytics.R
> +                                           lwr = quantile(x,0.025, na.rm = T)),
```suggestion
                             function(x) c(mean = mean(x,na.rm = TRUE),
                                           upr = quantile(x,0.975, na.rm = TRUE),
                                           lwr = quantile(x,0.025, na.rm = TRUE)),
```

2023-11-30 13:27 UTC, vandenman commented on R/predictiveAnalytics.R
> +        print("doing the bma plotting")
```suggestion
```

2023-11-30 13:27 UTC, vandenman commented on R/predictiveAnalytics.R
> +        )))
no `paste` within `gettext`

2023-11-30 22:11 UTC, petersen-f commented
@vandenman Thank you Don! I indeed found more examples where I did this wrong... But I fixed every gettext now.

2023-12-12 07:47 UTC, vandenman approved these changes

2023-12-12 07:47 UTC, merged